kind: PersistentVolume
apiVersion: v1
metadata:
  name: example-persistence
  labels:
    habitat: "true"
spec:
  capacity:
    storage: 5Gi
  # storageClassName: example-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/k8spv
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-persistent-habitat
spec:
  # the core/redis habitat service packaged as a Docker image
  image: kinvolk/redis-hab
  count: 3
  persistence:
    size: 1Gi
    # if not present, defaults to ""
    # storageClassName: example-storage
    mountPath: /tmp/yeah
  env:
    - name: HAB_REDIS
      value: '{ "protected-mode": "no" }'
  service:
    name: redis
    topology: leader
    # if not present, defaults to "default"
    group: foobar
